In [30]:
import pandas as pd
import numpy as np
from scipy.stats import chisquare

df = pd.read_csv('/content/drive/MyDrive/데이터 셋/P230605.csv', encoding='cp949')

print(df.head())
print(df.shape)
print(df.info())
print(df.describe())
print(df['코드'].value_counts())

   코드
0   4
1   2
2   4
3   4
4   4
(253, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   코드      253 non-null    int64
dtypes: int64(1)
memory usage: 2.1 KB
None
               코드
count  253.000000
mean     3.573123
std      0.890642
min      1.000000
25%      4.000000
50%      4.000000
75%      4.000000
max      4.000000
4    199
2     24
1     15
3     15
Name: 코드, dtype: int64

In [55]:
df_placebo = df.groupby('코드').size().reset_index(name='건수')
print(df_placebo)

total_count = len(df)

df_placebo['유형비율'] = df_placebo['건수'] / total_count
print(df_placebo)

result_1 = round((df_placebo['유형비율'][3]),3)
print(result_1)

   코드   건수
0   1   15
1   2   24
2   3   15
3   4  199
   코드   건수      유형비율
0   1   15  0.059289
1   2   24  0.094862
2   3   15  0.059289
3   4  199  0.786561
0.787

In [66]:
from scipy.stats import chisquare
import numpy as np

df_placebo['비율']= [0.05, 0.1, 0.05, 0.8]
print(df_placebo)

result2_chiq = chisquare(df_placebo['건수'], f_exp = df_placebo['비율'] * np.sum(total_count))
result2 = round(result2_chiq.statistic, 3)
print(result2)

result3 = round(result2_chiq.pvalue, 3)
print(result3)

   코드   건수      유형비율    비율
0   1   15  0.059289  0.05
1   2   24  0.094862  0.10
2   3   15  0.059289  0.05
3   4  199  0.786561  0.80
0.997
0.802

In [72]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

df= pd.read_csv('/content/drive/MyDrive/데이터 셋/P230606.csv', encoding='cp949')

print(df.shape)
print(df.head())
print(df.info())
print(df.describe())

(111, 4)
   O3  Solar  Wind  Temperature
0  41    190   7.4           67
1  36    118   8.0           72
2  12    149  12.6           74
3  18    313  11.5           62
4  23    299   8.6           65
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   O3           111 non-null    int64
 1   Solar        111 non-null    int64
 2   Wind         111 non-null    float64
 3   Temperature  111 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 3.6 KB
None
               O3       Solar        Wind  Temperature
count  111.000000  111.000000  111.000000   111.000000
mean    42.099099  184.801802    9.939640    77.792793
std     33.275969   91.152302    3.557713     9.529969
min      1.000000    7.000000    2.300000    57.000000
25%     18.000000  113.500000    7.400000    71.000000
50%     31.000000  207.000000    9.700000    79.000000
75%     62.000000  255.500000   11.500000    84.500000
max    168.000000  334.000000   20.700000    97.000000

In [107]:
x= df.drop(['Temperature'], axis=1)
y = df['Temperature']
print(x)
print(y)

md = LinearRegression()
md.fit(x,y)

result1 = round(float(md.coef_[0]),3)
print(result1)

     O3  Solar  Wind
0    41    190   7.4
1    36    118   8.0
2    12    149  12.6
3    18    313  11.5
4    23    299   8.6
..   ..    ...   ...
106  14     20  16.6
107  30    193   6.9
108  14    191  14.3
109  18    131   8.0
110  20    223  11.5

[111 rows x 3 columns]
0      67
1      72
2      74
3      62
4      65
       ..
106    63
107    70
108    75
109    76
110    68
Name: Temperature, Length: 111, dtype: int64
0.172

In [108]:
from scipy.stats import shapiro,levene, ttest_ind

nor = shapiro(df)
print(nor)

lev = levene(df['Wind'], y)

ttest = ttest_ind(df['Wind'],y)
result2 = round(ttest.pvalue, 3)
print(result2)

ShapiroResult(statistic=0.801748514175415, pvalue=6.430618656696367e-23)
0.0

In [109]:
new = pd.DataFrame({'O3':[10],'Solar': [90], 'Wind':[20]})

result3 = md.predict(new)
print(np.round(result3[0], 3))

68.334